apiVersion: batch/v1
kind: Job
metadata:
  name: wrist-ner-hpo-a100-germedbert-medbert-512-no-duplicates
  labels:
    app: wrist-ner-hpo-a100-germedbert-medbert-512-no-duplicates
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: wrist-ner-hpo-a100-germedbert-medbert-512-no-duplicates
    spec:
      priorityClassName: unimportant
      containers:
        - name: medbert
          image: registry.datexis.com/pgrundmann/medbert
          command: [
            "python3", "evaluation/hpo_ner_ct.py",
            "--num_classes",  "36",
            "--save_dir", "/tmp/wrist_ct",
            "--modelname", "GerMedBERT/medbert-512-no-duplicates",
            "--task", "wrist_ct",
            "--tmp_modelname",  "GerMedBERT/medbert-512-no-duplicates",
            "--storage_mode", "postgresql",
            "--train_filename", "/pvc/radiologie-benchmarks/wrist-xray-and-ct/train.csv",
            "--test_filename", "/pvc/radiologie-benchmarks/wrist-xray-and-ct/test.csv",
            "--val_filename", "/pvc/radiologie-benchmarks/wrist-xray-and-ct/val.csv",
            "--test", "True"
          ]
          envFrom:
            - secretRef:
                name: huggingface-auth
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: TOKENIZERS_PARALLELISM
              value: 'true'
            - name: NCCL_DEBUG
              value: 'INFO'
            - name: TRANSFORMERS_CACHE
              value: "/pvc/huggingface_cache"
            - name: HF_DATASETS_CACHE
              value: "/pvc/datasets_cache"
          resources:
            requests:
              cpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: medbert-pvc
              mountPath: /pvc
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: medbert-pvc
          persistentVolumeClaim:
            claimName: medbert-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never